# Generated by Django 4.0.2 on 2022-05-23 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoprite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created',)},
        ),
    ]
