# Generated by Django 4.0.5 on 2022-06-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoprite', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
